#define the sonar parameters
horizontalFOV: 130.0
transformation: 0.1
verticalAperture: 20.0
horizontalTopic: "/sonar_oculus_node/M750d/ping"
verticalTopic: "/sonar_oculus_node/M1200d/ping"

#define which implmentation we want to match the features
method: cpp # options are cpp or python

#do we want to see the feature images from CFAR? turn on to publish
visFeatures: True

#define the matching paramters
uncertaintyMax: .98
patchSize: 1

#define CFAR for the horizontal sonar
tcHorizontal: 20
gcHorizontal: 10
pfaHorizontal: .2
thresholdHorizontal: 50.

#define CFAR for the vertical sonar
tcVertical: 20
gcVertical: 10
pfaVertical: .2
thresholdVertical: 50.